### ISSUE TITLE
Test2-Workflow-0.000006 suggests not yet released Trace::Mask 0.000007

### ISSUE THREAD

**Issue by ppisar** [Test-More/Test2-Workflow#1]
META.json in Test2-Workflow-0.000006 reads:

```
         "suggests" : {
            "Sub::Name" : "0.11",
            "Sub::Util" : "1.40",
            "Trace::Mask" : "0.000007"
         }
```

But there is no 0.000007 version of Trace::Mask module on the CPAN. It's only suggestion, but still it would be great to release new Trace-Mask.

**Comment by exodist** [comment]
Yeah, I released those 2, planning to release a Trace::Mask the same day, but my change to Trace::Mask broke some tests, and I ran out of time to fix it :-(  I will release a new Trace::Mask as soon as I can.

**Comment by exodist** [comment]
just uploaded the new Trace::Mask.
