### ISSUE TITLE
Test2::Workflow Failing with latest Test2::Suite

### ISSUE THREAD

**Issue by bluefeet** [Test-More/Test2-Workflow#2]
Test2::Workflow v0.000009 (latest) Acceptance.t fails with the Test2::Suite v0.000032 (latest).  If I rollback to v0.000030 then Acceptance.t passes.

There are many failing tests on CPAN testers which demonstrate the errors.  But, it has to do with this particular type of TODO not actually triggering a TODO:

```
    tests bug => {todo => 'a bug'}, sub {
        ok(0, 'fail');
    };
```

If I change it to this it works:

```
    tests bug => sub {
        my $todo = todo 'a bug';
        ok(0, 'fail');
    };
```

**Comment by exodist** [comment]
Ah thanks. This is related to a bugfix I applied to Test2::Suite. I will try to get a fox out tonight.

**Comment by exodist** [comment]
just released fix to cpan

**Comment by bluefeet** [comment]
Thanks!
