### ISSUE TITLE
[PATCH] spelling fixes

### ISSUE THREAD

**Issue by gregoa** [Test-More/Test2-Workflow#8]
In Debian we are currently applying the following patch to
Test2-Workflow.
We thought you might be interested in it too.

```
Description: spelling fixes
Origin: vendor
Author: gregor herrmann <gregoa@debian.org>
Last-Update: 2016-10-30
```

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libtest2-workflow-perl.git/plain/debian/patches/spelling.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by exodist** [comment]
thanks!
